#!/bin/bash
set -euo pipefail

# ============================================================================
# MMM-Openclaw Mac Development Setup
# ============================================================================
# Sets up local MagicMirror + module for UI development on your Mac.
# Run once, then use dev.sh for daily workflow.
#
# Usage:
#   chmod +x scripts/setup-mac.sh
#   ./scripts/setup-mac.sh
#
# Prerequisites: Node.js >= 22, git
# ============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1"; exit 1; }
info() { echo -e "${BLUE}→${NC} $1"; }

echo ""
echo "🦞 MMM-Openclaw Development Setup"
echo "=================================="
echo ""

# --------------------------------------------------------------------------
# 1. Check prerequisites
# --------------------------------------------------------------------------
info "Checking prerequisites..."

if ! command -v node &>/dev/null; then
  err "Node.js not found. Install with: brew install node"
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 22 ]; then
  warn "Node.js $NODE_VERSION detected. OpenClaw recommends >= 22."
  warn "Run: brew install node@22"
fi

if ! command -v git &>/dev/null; then
  err "git not found. Install with: brew install git"
fi

if ! command -v npm &>/dev/null; then
  err "npm not found. Should come with Node.js."
fi

log "Prerequisites OK (Node $(node -v), npm $(npm -v))"

# --------------------------------------------------------------------------
# 2. Determine project root
# --------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
MM_DIR="$PROJECT_ROOT/.magicmirror-dev"
MODULE_SRC="$PROJECT_ROOT"

info "Project root: $PROJECT_ROOT"
info "MagicMirror dev instance: $MM_DIR"

# --------------------------------------------------------------------------
# 3. Clone/update MagicMirror for local development
# --------------------------------------------------------------------------
if [ -d "$MM_DIR" ]; then
  info "MagicMirror dev instance already exists, pulling updates..."
  cd "$MM_DIR"
  git pull --ff-only 2>/dev/null || warn "Could not pull MM updates (offline?)"
else
  info "Cloning MagicMirror for local development..."
  git clone --depth 1 https://github.com/MagicMirrorOrg/MagicMirror "$MM_DIR"
fi

cd "$MM_DIR"

if [ ! -d "node_modules" ]; then
  info "Installing MagicMirror dependencies (this takes a minute)..."
  npm install --no-audit --no-fund
else
  log "MagicMirror dependencies already installed"
fi

# --------------------------------------------------------------------------
# 4. Symlink our module into MagicMirror
# --------------------------------------------------------------------------
MODULE_LINK="$MM_DIR/modules/MMM-Openclaw"

if [ -L "$MODULE_LINK" ]; then
  log "Module symlink already exists"
elif [ -d "$MODULE_LINK" ]; then
  warn "Module directory exists but is not a symlink. Replacing..."
  rm -rf "$MODULE_LINK"
  ln -s "$MODULE_SRC" "$MODULE_LINK"
  log "Module symlinked (replaced directory)"
else
  ln -s "$MODULE_SRC" "$MODULE_LINK"
  log "Module symlinked: $MODULE_LINK → $MODULE_SRC"
fi

# --------------------------------------------------------------------------
# 5. Install module dependencies
# --------------------------------------------------------------------------
info "Installing MMM-Openclaw dependencies..."
cd "$MODULE_SRC"
npm install --no-audit --no-fund
log "Module dependencies installed"

# --------------------------------------------------------------------------
# 6. Generate MagicMirror config
# --------------------------------------------------------------------------
CONFIG_FILE="$MM_DIR/config/config.js"

info "Writing MagicMirror dev config..."
cat > "$CONFIG_FILE" << 'MMCONFIG'
/**
 * MagicMirror² Configuration — MMM-Openclaw Development
 *
 * This config is auto-generated by setup-mac.sh.
 * Edit as needed for your development workflow.
 */

let config = {
  address: "localhost",
  port: 8080,
  basePath: "/",
  ipWhitelist: ["127.0.0.1", "::fffd:127.0.0.1", "::1"],
  language: "en",
  locale: "en-US",
  timeFormat: 12,
  units: "imperial",
  electronOptions: {
    webPreferences: {
      webviewTag: true,
    },
  },

  modules: [
    // --- Context modules (keep the mirror feeling real) ---
    {
      module: "clock",
      position: "top_left",
      config: {
        timeFormat: 12,
        showDate: true,
        showSunTimes: false,
      },
    },
    {
      module: "calendar",
      header: "Family Calendar",
      position: "top_left",
      config: {
        maximumEntries: 5,
        calendars: [
          {
            fetchInterval: 60 * 60 * 1000,
            symbol: "calendar",
            url: "https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics",
          },
        ],
      },
    },
    {
      module: "compliments",
      position: "lower_third",
      config: {
        compliments: {
          anytime: ["Welcome home!", "Looking good today!"],
          morning: ["Good morning, sunshine!", "Rise and shine!"],
          afternoon: ["Hello, beautiful afternoon!", "Keep it up!"],
          evening: ["Wow, you survived another day!", "Relax and unwind."],
        },
      },
    },

    // --- MMM-Openclaw (our module) ---
    {
      module: "MMM-Openclaw",
      position: "bottom_bar",
      config: {
        // Point to mock gateway for local dev, or your real OpenClaw Gateway
        gatewayUrl: process.env.OPENCLAW_GATEWAY_URL || "ws://127.0.0.1:18789",
        gatewayToken: process.env.OPENCLAW_GATEWAY_TOKEN || "",

        // Display
        sessionName: "family-mirror",
        maxMessages: 8,
        showTypingIndicator: true,
        showConnectionStatus: true,
        showTimestamps: false,
        theme: "default",

        // Cross-module communication
        allowNotificationTriggers: true,
        broadcastResponses: true,

        // Auto-hide (0 = never)
        hideAfterInactivity: 0,
      },
    },
  ],
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }
MMCONFIG

log "MagicMirror config written"

# --------------------------------------------------------------------------
# 7. Create .env file for secrets
# --------------------------------------------------------------------------
ENV_FILE="$PROJECT_ROOT/.env"

if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" << 'ENVFILE'
# MMM-Openclaw Development Environment
# =====================================
# These are loaded by dev.sh and deploy.sh

# OpenClaw Gateway (your AWS instance)
OPENCLAW_GATEWAY_URL=ws://127.0.0.1:18789
OPENCLAW_GATEWAY_TOKEN=

# Raspberry Pi deployment target
PI_HOST=pi@raspberrypi.local
PI_MODULE_PATH=/home/pi/MagicMirror/modules/MMM-Openclaw

# Optional: Tailscale hostname for remote Pi
# PI_HOST=pi@your-pi.tail12345.ts.net
ENVFILE
  log "Created .env file (edit with your settings)"
else
  log ".env file already exists"
fi

# --------------------------------------------------------------------------
# 8. Create VS Code workspace settings
# --------------------------------------------------------------------------
VSCODE_DIR="$PROJECT_ROOT/.vscode"
mkdir -p "$VSCODE_DIR"

cat > "$VSCODE_DIR/settings.json" << 'VSCODE'
{
  "editor.formatOnSave": true,
  "editor.tabSize": 2,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "files.exclude": {
    "**/node_modules": true,
    "**/.git": true,
    ".magicmirror-dev": true
  },
  "search.exclude": {
    ".magicmirror-dev": true,
    "**/node_modules": true
  },
  "eslint.workingDirectories": ["."]
}
VSCODE

cat > "$VSCODE_DIR/launch.json" << 'LAUNCH'
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Mock Gateway",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/tools/mock-gateway.js",
      "console": "integratedTerminal"
    },
    {
      "name": "Mock Gateway (Demo Mode)",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/tools/mock-gateway.js",
      "args": ["--demo"],
      "console": "integratedTerminal"
    }
  ]
}
LAUNCH

log "VS Code workspace configured"

# --------------------------------------------------------------------------
# 9. Create .gitignore
# --------------------------------------------------------------------------
if [ ! -f "$PROJECT_ROOT/.gitignore" ]; then
  cat > "$PROJECT_ROOT/.gitignore" << 'GITIGNORE'
# Dependencies
node_modules/

# Local MagicMirror dev instance
.magicmirror-dev/

# Environment and secrets
.env
.env.local

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*

# IDE
.idea/
*.swp
*.swo
GITIGNORE
  log ".gitignore created"
else
  log ".gitignore already exists"
fi

# --------------------------------------------------------------------------
# 10. Init git if needed
# --------------------------------------------------------------------------
cd "$PROJECT_ROOT"
if [ ! -d ".git" ]; then
  git init
  git add -A
  git commit -m "feat: initial MMM-Openclaw project setup"
  log "Git repository initialized with initial commit"
else
  log "Git repository already exists"
fi

# --------------------------------------------------------------------------
# Done
# --------------------------------------------------------------------------
echo ""
echo "============================================"
echo -e "${GREEN}✓ Setup complete!${NC}"
echo "============================================"
echo ""
echo "Quick start:"
echo ""
echo "  1. Start the mock gateway:"
echo "     node tools/mock-gateway.js"
echo ""
echo "  2. In another terminal, start MagicMirror:"
echo "     ./scripts/dev.sh"
echo ""
echo "  3. MagicMirror opens in Electron. Use DevTools to test:"
echo "     MM.getModules().withClass('MMM-Openclaw')[0].sendQuery('Hello!')"
echo ""
echo "  4. Edit .env with your OpenClaw Gateway URL + token"
echo ""
echo "  5. Deploy to Pi when ready:"
echo "     ./scripts/deploy.sh"
echo ""
